SELECT LEFT(SALES_DATE, 10) AS SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT FROM ONLINE_SALE
-- AS : 부를 이름
WHERE SALES_DATE LIKE '2022-03%'
-- 2022년 3월 데이터만 가져오기 LIKE % -> %에 무엇이 와도 상관없음
-- 다른 방법 BETWEEN '2022-03-01' AND '2022-03-31'
UNION ALL
SELECT LEFT(SALES_DATE, 10) AS SALES_DATE, PRODUCT_ID, NULL AS USER_ID, SALES_AMOUNT FROM OFFLINE_SALE
WHERE SALES_DATE LIKE '2022-03%'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID